# Terraform Apply to {env} on Primary Region
name: Terraform Apply to {env}

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      terraform_changed:
        required: true
        type: string

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  terraform-apply:
    name: Terraform Apply
    if: inputs.terraform_changed == 'true'
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_GITHUB_ACTIONS_ROLE }}
          role-session-name: GithubWorkflow-TerraformDeployment-${{ inputs.environment }}
          aws-region: ${{ vars.AWS_PRIMARY_REGION }}
          role-duration-seconds: 900
          role-skip-session-tagging: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.3

      - name: Terraform Init
        working-directory: ./infra/terraform/environments/${{ inputs.environment }}/${{ vars.AWS_PRIMARY_REGION }}
        run: terraform init

      - name: Terraform Plan
        id: terraform-plan
        working-directory: ./infra/terraform/environments/${{ inputs.environment }}/${{ vars.AWS_PRIMARY_REGION }}
        run: terraform plan -out=${{ inputs.environment }}.tfplan

      - name: Terraform Apply
        working-directory: ./infra/terraform/environments/${{ inputs.environment }}/${{ vars.AWS_PRIMARY_REGION }}
        run: terraform apply -auto-approve ${{ inputs.environment }}.tfplan